export enum BaseGameStateTypes {
  READY = 'READY',
  VIEWING_START = 'VIEWING_START',
  ROLLING = 'ROLLING',
  WALKING = 'WALKING',
  DECIDING = 'DECIDING',
  AUCTION = 'AUCTION',
  BANKRUPT = 'BANKRUPT',
  TRADING = 'TRADING',
  VIEWING_END = 'VIEWING_END',
  END_TURN = 'END_TURN',
}
